"""
Django settings for kurs_plan project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
WEBTOOL_TEMPLATE_ROOT = BASE_DIR / 'webtool_template'

# Local package (also declared in pyproject.toml for uv).
sys.path.insert(0, str(WEBTOOL_TEMPLATE_ROOT / 'src'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ek@ag0ofh9oq20sj4y8ir6z4anwfzwi^hzpbr+y8q*kyqt!7^='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webtool_template.apps.WebtoolTemplateConfig',
    'courses',
    'specializations',
    'planner',
    'manage',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kurs_plan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            WEBTOOL_TEMPLATE_ROOT / 'templates',
            WEBTOOL_TEMPLATE_ROOT / 'components',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kurs_plan.context_processors.webtool_shell',
            ],
        },
    },
]

WSGI_APPLICATION = 'kurs_plan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    WEBTOOL_TEMPLATE_ROOT / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

WEBTOOL_TEMPLATE = {
    'PREFIX': 'kursplan',
    'LAYOUT_MODE': 'template',
    'FOOTER_TEXT': 'Kurs-Plan — University of Basel',
    'HOME_URL_RESOLVER': 'kurs_plan.navigation.home_url_for_request',
    'FONT_URLS': [
        (
            'https://fonts.googleapis.com/css2?family=Inter:wght@400;600'
            '&family=PT+Serif:wght@400;700&display=swap'
        ),
    ],
}


# Authentication redirects for the custom management UI.
LOGIN_URL = 'manage:login'
LOGIN_REDIRECT_URL = 'manage:dashboard'
LOGOUT_REDIRECT_URL = 'manage:login'
