# Generated by Django 6.0.5 on 2026-05-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('credit_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='credit points')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.coursecategory')),
                ('modules', models.ManyToManyField(blank=True, related_name='courses', to='courses.module')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
