# Generated by Django 6.0.5 on 2026-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecategory_display_order_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
