# Generated by Django 6.0.5 on 2026-05-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationModuleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_credit_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='required credit points')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialization_requirements', to='courses.module')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_requirements', to='specializations.specialization')),
            ],
            options={
                'ordering': ['specialization', 'display_order', 'module'],
                'constraints': [models.UniqueConstraint(fields=('specialization', 'module'), name='unique_specialization_module')],
            },
        ),
    ]
