# Generated by Django 6.0.5 on 2026-05-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0002_specializationmodulerequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalRequirementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('minimum_credits_across_modules', 'Minimum credits across modules')], max_length=64)),
                ('required_credit_points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='required credit points')),
                ('active', models.BooleanField(default=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_requirement_rules', to='specializations.specialization')),
            ],
            options={
                'ordering': ['specialization', 'name'],
            },
        ),
    ]
