# Generated by Django 6.0.5 on 2026-05-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
        ('specializations', '0003_additionalrequirementrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalrequirementrule',
            name='modules_included',
            field=models.ManyToManyField(blank=True, help_text='Modules whose course credits this rule aggregates over.', related_name='additional_requirement_rules', to='courses.module', verbose_name='modules included'),
        ),
    ]
