# Generated by Django 6.0.5 on 2026-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'site text',
                'verbose_name_plural': 'site texts',
                'ordering': ['key'],
            },
        ),
    ]
